language: java

jdk:
    - oraclejdk8

services:
  - docker

before_install:
- docker pull docker.elastic.co/elasticsearch/elasticsearch:5.5.0

script: mvn clean verify -Dskip.integration=false

after_success:
  - mvn clean cobertura:cobertura coveralls:report