version: 2.1

executors:
  jdk:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

jobs:
  test:
    executor: jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn clean verify
      - run: mvn cobertura:cobertura coveralls:report

workflows:
  version: 2
  test:
    jobs:
      - test