swagger: '2.0'
info:
  title: Ontology Services
  description: A set of web-services related to ontology information.
  version: 0.0.1
  license:
    name: BSD
    url: 'http://opensource.org/licenses/BSD-3-Clause'
  termsOfService: 'https://github.com/broadinstitute/consent'
schemes:
  - https
  
paths:

  /schema:
    get:
      summary: Data Use Schema
      description: The Data Use Schema for use in defining structured data use restrictions and data access requests.
      tags:
        - Schema
      responses:
        200:
          description: The schema
        default:
          description: Unexpected error

  /schema/translate:
    post:
      summary: Translate Data Use Schema
      description: Translate a Data Use Schema to a Use Restriction
      tags:
        - Schema
      parameters:
        - name: schemaString
          in: body
          description: JSON formatted Data Use Schema object
          required: true
          schema:
            $ref: '#/definitions/DataUseSchema'
      responses:
        200:
          description: The use restriction
        400:
          description: invalid data use schema format
        default:
          description: Unexpected error

  '/translate':
  
    post:
      summary: translate
      description: The Translate service will render an English-language version of a consent or research purpose.
      produces: 
        - text/plain
      parameters:
        - name: for
          in: query
          description: Translates a research purpose or a consent. (purpose or sampleset)
          required: true
          type: string
        - name: body
          in: body
          description: Restriction
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/Restriction'
      tags:
        - Translate
      responses:
        '200':
          description: Successful translation.
        default:
          description: Unexpected error

  '/match':
  
    post:
      summary: match
      description: The Match service will render a response of true or false between a Consent and a Research Purpose.
      parameters:
        - name: body
          in: body
          description: Consent and Purpose Use Restrictions.
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/matchRestrictions'
      tags:
        - Match
      responses:
        '200':
          description: Successful matching.
        default:
          description: Unexpected error
          
            
  '/validate/userestriction':

      post:
        summary: validate
        description: The Validate service will check If the posted Use Restriction has the correct format and content.
        parameters:
          - name: body
            in: body
            description: Restriction
            required: true
            schema:
              type: array
              items:
                $ref: '#/definitions/Restriction'
        tags:
          - Validate
        responses:
          '200':
            description: Successful validation. True for valid restriction and False for invalid.
          default:
            description: Unexpected error

  '/autocomplete':
  
    get:
      summary: autocomplete
      description: Ontologies can be queried based on term; type and count. This provides an easy filtering mechanism that allows users to select ontology terms that are applicable to consents or research purposes.
      parameters:
        - name: q
          in: query
          description: The query term (word fragment) which the service should try and complete.
          required: true
          type: string
        - name: types
          in: query
          description: An optional list (comma-separated) of term types; if specified only those types will be searched for autocomplete suggestions. If left unspecified all available types will be searched. Available values for this service will initially be disease and organization.
          required: false
          type: string
        - name: count
          in: query
          description: An optional limit on the number of autosuggested results that are returned. Default value is 20.
          required: false
          type: number
      tags:
        - Autocomplete
      responses:
        '200':
          description: Array of results.
        default:
          description: Unexpected error

  '/search':
  
    get:
      summary: search
      description: Find ontologies based on the id.
      parameters:
        - name: id
          in: query
          description: The ontology id which the service us to find it (e.g. DOID_4).
          required: true
          type: string
      tags:
        - Search
      responses:
        '200':
          description: The given id was found. Json result with ontology information.
        default:
          description: Unexpected error


definitions:
  Restriction:
    type: object
    properties:
      type:
        type: string
        description: 'Conector (and, or)'
      operands:
        type: array
        items:
          type: string
        description: Array of ontologies.

  matchRestrictions:
    type: object
    properties:
      purpose:
        type: object
        properties:
          type: 
            type: string
          operands:
            type: array
            items:
              type: string
              description: Array of ontologies.
      consent:
        type: object
        properties:
          type: 
            type: string
          operands:
            type: array
            items:
              type: string
              description: Array of ontologies.
  DataUseSchema:
    type: object
    description: JSON-standard packet of a data use description as defined by the Data Use Schema
    example: |
      {
        "generalUse": false,
        "hmbResearch": true,
        "diseaseRestrictions": ["http://purl.obolibrary.org/obo/DOID_602", "http://purl.obolibrary.org/obo/DOID_162"],
        "gender": "Male",
        ...
        additional JSON-standard fields as
        defined by the Data Use schema
        ...
      }
