name: Maven
on: [pull_request]
jobs:
  package:
    name: Automation Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Gatling Tests
        run: |
          mvn -v
          mvn clean gatling:test
      - name: Copy stats to classpath
        run: cp target/gatling/testrunner-*/js/stats.json target/classes
      - name: Format the results
        env:
          MAVEN_OPTS: -Dexec.mainClass="performance.ResultsFormatter" -Dexec.classpathScope=test
        run: mvn test-compile exec:java
