name: Performance
on: workflow_dispatch
jobs:
  performance-tests:
    name: Performance/Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Run Gatling Tests
        run: |
          mvn -v
          mvn clean gatling:test --no-transfer-progress
      - name: Format Gatling Tests
        run: |
          mv ./target/gatling/testrunner* ./target/gatling/test
          cp ./target/gatling/test/js/stats.json ./src/test/resources
          cp ./target/gatling/test/simulation.log ./src/test/resources
          mvn test-compile
          mvn exec:java -Dexec.mainClass=org.broadinstitute.dsp.ontology.performance.parsers.LogParser -Dexec.classpathScope=test

# TODO: Instantiate a BEE environment to run tests against
# TODO: Upload test results to QA BQ
# TODO: Move this to be dependent on build.yaml.
# ... this can't be done until this is on the default branch
  #  workflow_run:
  #    workflows: [Build]
  #    types:
  #      - completed
  #    if: ${{ github.event.workflow_run.conclusion == 'success' }}

# Relevant docs for future development:
# * https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
# * https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
