name: Performance
on: workflow_dispatch
jobs:
  performance-tests:
    name: Performance/Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Gatling Tests
        run: |
          mvn -v
          mvn clean gatling:test --no-transfer-progress

# TODO: Instantiate a BEE environment to run tests against
# TODO: Upload test results to QA BQ
# TODO: Move this to be dependent on build.yaml.
# ... this can't be done until this is on the default branch
  #  workflow_run:
  #    workflows: [Build]
  #    types:
  #      - completed
  #    if: ${{ github.event.workflow_run.conclusion == 'success' }}
